package agi_sdk.helpers;

public enum Course {
    GNOME,
    DRAYNOR,
    AL_KHARID,
    VARROCK,
    CANIFIS,
    COLOSSAL_WYRM_PROGRESSIVE,
    BASIC_COLOSSAL_WYRM,
    FALADOR,
    SEERS,
    SEERS_TELEPORT,
    ADVANCED_COLOSSAL_WYRM,
    POLLNIVNEACH,
    RELLEKKA,
    ARDOUGNE,
    PROGRESSIVE_TO_50,
}